# Generated by Django 2.2.9 on 2021-04-25 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_amount',
            new_name='amount',
        ),
    ]
