# Generated by Django 2.2.9 on 2021-04-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210426_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='book_name',
            new_name='books',
        ),
    ]
